apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-dep
spec:
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: image-persist
          persistentVolumeClaim:
            claimName: log-ping-pvc
      containers:
        - name: the-project
          image: imbekrishna/the-project:1.12
          volumeMounts:
            - name: image-persist
              mountPath: /app/data
