apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-ping-pvc
spec:
  storageClassName: shared-log-ping-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
